name: Docker Image CI

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker so that we can build and push images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub using your secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image and tag it with a version
    - name: Build and tag Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-knn-app:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/flask-knn-app:latest ${{ secrets.DOCKER_USERNAME }}/flask-knn-app:${{ github.sha }}

    # Push both the 'latest' tag and the specific commit SHA tag to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-knn-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-knn-app:${{ github.sha }}
